version: "3.9"

services:
  app:
    build:
      context: ./FeatureMe
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - MONGODB_URI=mongodb://mongo:27017/featureme
      - spring.cloud.aws.credentials.access-key=${AWS_ACCESSKEYID}
      - spring.cloud.aws.credentials.secret-key=${AWS_SECRETACCESSKEY}
      - spring.cloud.aws.region.static=${AWS_REGION}
      - spring.cloud.aws.s3.bucket=${AWS_S3BUCKET}
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION_MS}
      - stripe.api.key= ${STRIPE_API_KEY}
      - stripe.api.secret=${STRIPE_SECRET_KEY}
      - stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
      - resend.api.key=${RESEND_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DATABASE=0
    ports:
      - "8080:8080"  # Backend API on localhost:8080
    restart: unless-stopped

  frontend:
    build:
      context: ./react-feature
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Frontend on localhost:3000
    restart: unless-stopped

  # Optional Mongo container for local dev
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # Redis for rate limiting and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
