version: "3.9"

services:
  app:
    build:
      context: ./FeatureMe
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - MONGODB_URI=mongodb://mongo:27017/featureme
      - spring.data.mongodb.database=${MONGO_DATABASE}
      - spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
      - spring.cloud.aws.credentials.access-key=${aws_accessKeyId}
      - spring.cloud.aws.credentials.secret-key=${aws_secretAccessKey}
      - spring.cloud.aws.region.static=${aws_region}
      - spring.cloud.aws.s3.bucket=${aws_s3bucket}
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION_MS}
      - stripe.api.key= ${public_key}
      - stripe.api.secret=${secret_key}
      - stripe.webhook.secret=${webhook_secret}
      - resend.api.key=${resend_api_key}
    ports:
      - "8080:8080"  # Backend API on localhost:8080
    restart: unless-stopped

  frontend:
    build:
      context: ./react-feature
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Frontend on localhost:3000
    restart: unless-stopped

  # Optional Mongo container for local dev
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
